server:
    port: 8081

spring:
    datasource:
        url: jdbc:mysql://localhost:3307/commentsdb
        username: root
        password: toor
    jpa:
        hibernate:
            ddl-auto: create