server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postsdb
        username: root
        password: toor
    jpa:
        hibernate:
            ddl-auto: create
    kafka:
        consumer:
            bootstrap-servers: localhost:9094